---
helmDefaults:
  tillerless: true
  wait: false
releases:
  - name: mongodb-kubernetes
    namespace: {{ requiredEnv "NS" }}
    chart: ./charts
    values:
    - ./charts/values/{{ requiredEnv "ENV" }}/values.yaml
