apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "mongodb-kubernetes.name" . }}-init
  namespace: {{ .Release.Namespace }}
data:
{{- if .Values.mms.enabled }}
  omCommon.py: |
{{ .Files.Get "init/omCommon.py" | indent 4 }}
  deployer.py: |
{{ .Files.Get "init/deployer.py" | indent 4 }}
  agent.py: |
{{ .Files.Get "init/agent.py" | indent 4 }}
  alerts.json: |
{{ .Files.Get "init/alerts.json" | indent 4 }}
  mongod.conf: |
{{ toYaml .Values.mms.config | indent 4 }}
{{ toYaml .Values.configMap | indent 4 }}
{{ else }}
  rs.py: |
{{ .Files.Get "init/rs.py" | indent 4 }}
  mongod.conf: |
{{ toYaml .Values.configMap | indent 4 }}
{{ end }}